services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_DB: db-dev
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728
    ports:
      - "5432:5432"
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data

volumes:
  minio-data:

