spring:
  liquibase:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db-dev
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  application:
    name: cloud-file-storage
  mvc:
    log-resolved-exception: false