spring:
  liquibase:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db-dev
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  application:
    name: cloud-file-storage
  mvc:
    log-resolved-exception: false

minio:
  endpoint: http://127.0.0.1:9000 #MINIO_ENDPOINT
  credentials:
    access_key: K81UxdzN93zfAyCbkCPd #MINIO_ACCESS_KEY
    secret_key: 263hoaaEkTkK49ZkrWRs9gVVdQS2o1hF0y7M8zRi #MINIO_SECRET_KEY