spring:
  liquibase:
    enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db-dev
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: none

  application:
    name: cloud-file-storage

  mvc:
    log-resolved-exception: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  data:
    redis:
      host: localhost
      port: 6379
      password: password

  session:
    timeout: 3600

  minio:
    endpoint: http://127.0.0.1:9000
    username: root
    password: password
    bucket_name: user-files
