spring:

  liquibase:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none

  application:
    name: cloud-file-storage

  mvc:
    log-resolved-exception: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  profiles:
    default: dev

  session:
    timeout: 3600

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}

  minio:
    endpoint: ${MINIO_URL}
    username: ${MINIO_USER}
    password: ${MINIO_PASSWORD}
    bucket_name: ${MINIO_BUCKET_NAME}


