#spring:
#  devtools:
#    add-properties: true
#  minio:
#    endpoint: http://127.0.0.1:9000
#    username: root
#    password: password
#    bucket_name: user-files
#
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      password: password
#
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/db-dev
#    username: root
#    password: password