spring:
  liquibase:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db-dev
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  application:
    name: cloud-file-storage
  mvc:
    log-resolved-exception: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    redis:
      host: localhost
      port: 6379
      password: password


minio:
  endpoint: http://127.0.0.1:9000 #MINIO_ENDPOINT
  credentials:
    access_key: pusdXdniq4rhH7ka6XQy #MINIO_ACCESS_KEY
    secret_key: PfaWKgmdxdBgxg0HEQcbnJWLWucV8LiVwxs0N00F #MINIO_SECRET_KEY